spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8080  # Directly pointing to the service's URI
          predicates:
            Path=/user/**
server:
  port: 9091
